### ISSUE TITLE
Any plans to support AMP (Amazon Managed Prometheus) ?

### ISSUE THREAD

**Issue by ebolwidt** [huksley/prometheus-remote-write#1]
Writing (with remote-write) to AMP requires AWS Sigv4 authentication.
Do you have any plans to support that as an authentication mechanism?

**Comment by huksley** [comment]
Do you have more info on that? I have no idea how it work, but would like to try.

**Comment by ebolwidt** [comment]
I've found a way to do it using the "fetch" argument in the Options to pushTimeseries.

npm module ["aws-sigv4-fetch"](https://www.npmjs.com/package/aws-sigv4-fetch) has a function "createSignedFetcher" that creates a node-fetcher compatible fetcher function that performs sigv4 authentication.

For AWS's managed prometheus service, use the service name "aps" when you call "createSignedFetcher".

**Comment by huksley** [comment]
Added to readme, thanks @ebolwidt 👍
