### ISSUE TITLE
X-Scope-OrgID header 

### ISSUE THREAD

**Issue by ShazotiHashimoto** [huksley/prometheus-remote-write#4]
Hi
This package is great, thanks for sharing..
I have one query regarding the X-Scope-OrgID header thats required when pushing to Grafana Mimir Prometheus. Would it be possible to cater for additional header fields when calling the pushTimeseries function.

I could suggest that the options var has a headers tag that you could add that would cater for any additional headers

**Comment by huksley** [comment]
Check it out `npm i prometheus-remote-write^0.4.0`

**Comment by ShazotiHashimoto** [comment]
Oh wow thanks man you are awesome
