### ISSUE TITLE
prom-client metrics

### ISSUE THREAD

**Issue by raineorshine** [huksley/prometheus-remote-write#5]
Does this library support remote writing prom-client’s [default metrics](https://github.com/siimon/prom-client/blob/master/example/default-metrics.js)? Thanks :).

**Comment by huksley** [comment]
you can use any metrics you want, just pass them as object to pushMetrics:
```js
await pushMetrics(
  {
    process_cpu_user_seconds_total: 0.001801
  }, 
  options
)
```
